language: ruby
sudo: required
services: docker
env:
  matrix:
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-debian-8
    - INSTANCE=default-debian-sid

matrix:
  allow_failures:
    - env: INSTANCE=default-debian-sid

rvm:
  # 2.1.0 is not supported anymore by chef-zero
  # 2.2.0 fails due to https://github.com/flori/json/issues/253
  - 2.3.1
  - 2.4.0

gemfile:
  Gemfile

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER

script:
  - bundle exec rspec --format=d --color */*/spec/*rb
  - bundle exec rubocop --display-cop-names -c .rubocop.yml
  - ./scripts/run_foodcritic
  - bundle exec kitchen verify $INSTANCE

before_deploy:
  - openssl aes-256-cbc -K $encrypted_9d2e88e318b2_key -iv $encrypted_9d2e88e318b2_iv -in supermarket.pem.enc -out supermarket.pem -d

deploy:
  - provider: script
    skip_cleanup: true
    script: PATH="${TRAVIS_BUILD_DIR}/bin:$PATH" ./scripts/supermarket_push
