language: ruby
sudo: required
services: docker
env:
  matrix:
    - INSTANCE=default-centos-6
    - INSTANCE=default-centos-7
    - INSTANCE=default-ubuntu-1604
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=default-debian-9
    - INSTANCE=default-debian-sid

matrix:
  allow_failures:
    - env: INSTANCE=default-debian-sid

rvm:
  # 2.1.0 is not supported anymore by chef-zero
  # 2.2.0 fails due to https://github.com/flori/json/issues/253
  - 2.3.1
  - 2.4.0

gemfile:
  Gemfile

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
  - bundle update

script:
  - shellcheck ./scripts/*
  - ./scripts/run_chefspec
  - ./scripts/run_rubocop .rubocop.yml
  - ./scripts/run_foodcritic
  - bundle exec kitchen verify $INSTANCE

# Disabling deploy until we sort out Supermarket issues t39456893
# jobs:
#   include:
#     - stage: supermarket deploy
#       rvm: 2.4
#       env: INSTANCE=default-centos-7
#       script:
#         - echo "Deploying cookbooks to supermarket"
#         - openssl aes-256-cbc -K $encrypted_9d2e88e318b2_key -iv $encrypted_9d2e88e318b2_iv -in supermarket.pem.enc -out supermarket.pem -d
#       deploy:
#         provider: script
#         skip_cleanup: true
#         script: PATH="${TRAVIS_BUILD_DIR}/bin:$PATH" ./scripts/supermarket_push
